package v3

import "github.com/baidubce/bce-sdk-go/services/bes/v3/api"

const (
	HEADER_REGION = api.HEADER_REGION

	URI_PREFIX_V3 = api.URI_PREFIX_V3
	URI_CLUSTERS  = api.URI_CLUSTERS
)

const (
	PAYMENT_POSTPAID = api.PAYMENT_POSTPAID
	PAYMENT_PREPAID  = api.PAYMENT_PREPAID
)

const (
	ENGINE_OPENSEARCH     = api.ENGINE_OPENSEARCH
	ENGINE_TYPE_COMMUNITY = api.ENGINE_TYPE_COMMUNITY
)

const (
	NODE_SPEC_TYPE_DATA             = api.NODE_SPEC_TYPE_DATA
	NODE_SPEC_TYPE_DATA_WARM        = api.NODE_SPEC_TYPE_DATA_WARM
	NODE_SPEC_TYPE_DATA_COLD        = api.NODE_SPEC_TYPE_DATA_COLD
	NODE_SPEC_TYPE_DEDICATED_MASTER = api.NODE_SPEC_TYPE_DEDICATED_MASTER
	NODE_SPEC_TYPE_COORDINATING     = api.NODE_SPEC_TYPE_COORDINATING
	NODE_SPEC_TYPE_DASHBOARDS       = api.NODE_SPEC_TYPE_DASHBOARDS
	NODE_SPEC_TYPE_ML               = api.NODE_SPEC_TYPE_ML
)

const (
	RESIZE_MODE_DIRECT     = api.RESIZE_MODE_DIRECT
	RESIZE_MODE_ROLLING    = api.RESIZE_MODE_ROLLING
	RESIZE_MODE_COLD       = api.RESIZE_MODE_COLD
	RESIZE_MODE_BLUE_GREEN = api.RESIZE_MODE_BLUE_GREEN
)

const (
	ACCESS_TYPE_OPENSEARCH = api.ACCESS_TYPE_OPENSEARCH
	ACCESS_TYPE_DASHBOARDS = api.ACCESS_TYPE_DASHBOARDS
)

const (
	NETWORK_TYPE_PUBLIC  = api.NETWORK_TYPE_PUBLIC
	NETWORK_TYPE_PRIVATE = api.NETWORK_TYPE_PRIVATE
)

const (
	UPGRADE_TYPE_ENGINE = api.UPGRADE_TYPE_ENGINE
	UPGRADE_TYPE_KERNEL = api.UPGRADE_TYPE_KERNEL
)

const (
	UPGRADE_OPERATION_CHECK   = api.UPGRADE_OPERATION_CHECK
	UPGRADE_OPERATION_UPGRADE = api.UPGRADE_OPERATION_UPGRADE
)

const (
	RESTART_TYPE_CLUSTER = api.RESTART_TYPE_CLUSTER
	RESTART_TYPE_NODE    = api.RESTART_TYPE_NODE
)

const (
	RESTART_MODE_BLUE_GREEN = api.RESTART_MODE_BLUE_GREEN
	RESTART_MODE_ROLLING    = api.RESTART_MODE_ROLLING
	RESTART_MODE_FORCE      = api.RESTART_MODE_FORCE
)

const (
	BATCH_UNIT_COUNT   = api.BATCH_UNIT_COUNT
	BATCH_UNIT_PERCENT = api.BATCH_UNIT_PERCENT
)

const (
	PLUGIN_VERSION_STATUS_PRE_INSTALLED = api.PLUGIN_VERSION_STATUS_PRE_INSTALLED
	PLUGIN_VERSION_STATUS_INSTALLED     = api.PLUGIN_VERSION_STATUS_INSTALLED
	PLUGIN_VERSION_STATUS_INSTALLING    = api.PLUGIN_VERSION_STATUS_INSTALLING
	PLUGIN_VERSION_STATUS_UNINSTALLING  = api.PLUGIN_VERSION_STATUS_UNINSTALLING
	PLUGIN_VERSION_STATUS_UNINSTALLED   = api.PLUGIN_VERSION_STATUS_UNINSTALLED
)

const (
	DIAGNOSIS_GRADE_SAFE      = api.DIAGNOSIS_GRADE_SAFE
	DIAGNOSIS_GRADE_LOW_RISK  = api.DIAGNOSIS_GRADE_LOW_RISK
	DIAGNOSIS_GRADE_HIGH_RISK = api.DIAGNOSIS_GRADE_HIGH_RISK
	DIAGNOSIS_GRADE_ERROR     = api.DIAGNOSIS_GRADE_ERROR
)

const (
	SCHEDULE_TYPE_DELETE      = api.SCHEDULE_TYPE_DELETE
	SCHEDULE_TYPE_ROLLOVER    = api.SCHEDULE_TYPE_ROLLOVER
	SCHEDULE_TYPE_FORCE_MERGE = api.SCHEDULE_TYPE_FORCE_MERGE
)

const (
	SCHEDULE_STATUS_SUCCESS = api.SCHEDULE_STATUS_SUCCESS
	SCHEDULE_STATUS_ERROR   = api.SCHEDULE_STATUS_ERROR
	SCHEDULE_STATUS_DOING   = api.SCHEDULE_STATUS_DOING
)
